const STD = [
  "/images/proof-mosquito.jpg",
  "/images/proof-ticks.jpg",
  "/images/proof-spider.jpg",
  "/images/size-guide-jacket.png",
  "/images/size-guide-fittype.png",
  "/images/size-guide-chart.png",
];

export const products = [
  {
    id: "ba-jacket-men",
    name: "Bug Away Jacket — Men",
    category: "MEN",
    price: 45,
    badge: "Best Seller",
    colors: ["Sage Green", "Stone Gray", "Arctic White"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL", "XXXL"],
    desc: "Full-coverage mesh jacket for men. Drawstring hood, zip closure and side pockets. Pairs perfectly with our Bug Away Pants for complete 360° tick protection. Chemical-free, lightweight and breathable.",
    features: ["Drawstring hood", "Zip closure", "Side pockets", "Noseeum-grade mesh", "Weight: < 45g", "UPF 30+"],
    images: [
      "/images/jacket-men-white-front.jpg",
      "/images/jacket-men-white-side.jpg",
      "/images/jacket-men-white-back.jpg",
      "/images/jacket-flatlay-white.jpg",
      "/images/jacket-men-lifestyle-birdwatching.jpg",
      "/images/jacket-men-lifestyle-forest-walking.jpg",
      "/images/jacket-men-lifestyle-bicycle-forest.jpg",
      "/images/detail-collage-white.jpg",
      ...STD,
    ],
  },
  {
    id: "ba-pants-men",
    name: "Bug Away Pants — Men",
    category: "MEN",
    price: 45,
    badge: "Best Seller",
    colors: ["Sage Green", "Stone Gray", "Arctic White"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL", "XXXL"],
    desc: "Tick-protection pants for men with integrated foot cover. The pant leg and foot are one continuous piece of mesh — no gap at the ankle, no entry point for ticks. Lightweight, breathable and chemical-free.",
    features: ["Integrated foot cover", "Elastic waistband", "Noseeum-grade mesh", "Weight: < 35g", "Machine washable"],
    images: [
      "/images/pants-men-white-front.jpg",
      "/images/pants-men-white-side.jpg",
      "/images/pants-men-white-back.jpg",
      "/images/pants-men-green-front.jpg",
      "/images/pants-detail-feet-grass.jpg",
      "/images/pants-lifestyle-feet-closeup.jpg",
      "/images/jacket-men-lifestyle-forest-walking.jpg",
      "/images/detail-collage-white.jpg",
      ...STD,
    ],
  },
  {
    id: "ba-jacket-women",
    name: "Bug Away Jacket — Women",
    category: "WOMEN",
    price: 45,
    badge: "Best Seller",
    colors: ["Sage Green", "Stone Gray", "Arctic White"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL", "XXXL"],
    desc: "Full-coverage mesh jacket for women. Slim tailored fit, drawstring hood and zip closure. Perfect as a base layer for hiking, gardening and outdoor adventures. Chemical-free and breathable.",
    features: ["Slim tailored fit", "Drawstring hood", "Zip closure", "Noseeum-grade mesh", "Weight: < 45g", "UPF 30+"],
    images: [
      "/images/jacket-women-white-front.jpg",
      "/images/jacket-women-white-detail.jpg",
      "/images/jacket-women-lifestyle-meadow-sunset.jpg",
      "/images/jacket-women-lifestyle-phone-forest.jpg",
      "/images/jacket-women-lifestyle-gardening.jpg",
      "/images/jacket-women-lifestyle-gardening-closeup.jpg",
      "/images/detail-collage-white.jpg",
      ...STD,
    ],
  },
  {
    id: "ba-pants-women",
    name: "Bug Away Pants — Women",
    category: "WOMEN",
    price: 45,
    badge: null,
    colors: ["Sage Green", "Stone Gray", "Arctic White"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL", "XXXL"],
    desc: "Tick-protection pants for women with integrated foot cover. One continuous piece of mesh from waist to toe — no gap, no entry point. Tailored fit, lightweight and breathable.",
    features: ["Integrated foot cover", "Tailored fit", "Elastic waistband", "Noseeum-grade mesh", "Weight: < 35g", "Machine washable"],
    images: [
      "/images/pants-women-white-front.jpg",
      "/images/pants-women-white-side.jpg",
      "/images/pants-women-white-back.jpg",
      "/images/pants-women-lifestyle-picnic-lake.jpg",
      "/images/pants-women-lifestyle-stars-field.jpg",
      "/images/pants-detail-feet-grass.jpg",
      "/images/detail-collage-white.jpg",
      ...STD,
    ],
  },
  {
    id: "ba-combo-adults",
    name: "Bug Away Combo Set — Jacket + Pants",
    category: "BUNDLES",
    price: 79,
    badge: "Best Seller",
    colors: ["Sage Green", "Stone Gray", "Arctic White"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL", "XXXL"],
    desc: "Complete tick protection in one set. Bug Away Jacket + Bug Away Pants bundled together — save €11 compared to buying separately. Chemical-free, lightweight noseeum-grade mesh with integrated foot cover.",
    features: ["Jacket + pants included", "Save €11 vs separate", "Integrated foot cover", "Noseeum-grade mesh", "Full 360° coverage"],
    images: [
      "/images/combo-lifestyle-couple-forest-green.jpg",
      "/images/combo-lifestyle-couple-forest-white.jpg",
      "/images/combo-lifestyle-couple-coffee-tent.jpg",
      "/images/combo-lifestyle-group-campfire-green.jpg",
      "/images/combo-lifestyle-woman-picnic-lake.jpg",
      "/images/combo-lifestyle-couple-beach-sunset.jpg",
      "/images/jacket-men-white-front.jpg",
      "/images/pants-men-white-front.jpg",
      "/images/detail-collage-white.jpg",
      ...STD,
    ],
  },
  {
    id: "ba-kids-set",
    name: "Bug Away Kids Set",
    category: "KIDS",
    price: 79,
    badge: "Best Seller",
    colors: ["Sage Green", "Sky Blue"],
    sizes: ["2-4Y", "4-6Y", "6-8Y", "8-10Y", "10-12Y"],
    desc: "Complete tick protection for kids. Jacket + pants set designed for safe outdoor play. Safe elastic at the hood (no drawstrings), integrated foot cover and extra pockets for nature treasures.",
    features: ["Jacket + pants included", "Safe elastic hood (no drawstrings)", "Integrated foot cover", "Extra pockets", "Gentle on sensitive skin", "Machine washable"],
    images: [
      "/images/kids-set-green-flatlay.jpg",
      "/images/kids-lifestyle-forest-playing.jpg",
      "/images/kids-lifestyle-jumping-stream.jpg",
      "/images/detail-collage-green.jpg",
      "/images/proof-mosquito.jpg",
      "/images/proof-ticks.jpg",
      "/images/proof-spider.jpg",
      "/images/size-guide-chart.png",
    ],
  },
];

export const reviews = [
  { id: 1, name: "Maaike V.", rating: 5, text: "Finally something that actually keeps ticks away. Wore it hiking all weekend — not a single bite.", product: "ba-jacket-men" },
  { id: 2, name: "James R.", rating: 5, text: "My whole family wears these now. Kids can play in the forest without us constantly checking.", product: "ba-kids-set" },
  { id: 3, name: "Sophie L.", rating: 5, text: "The integrated foot cover is genius. No more tucking trousers into socks.", product: "ba-pants-women" },
  { id: 4, name: "Bart M.", rating: 4, text: "Lightweight, breathable, does exactly what it says. Great for gardening too.", product: "ba-jacket-women" },
];
