export const products = [
  {
    id: "ba-pants-men",
    name: "Bug Away Pants — Men",
    shortName: "Pants Men",
    price: 69.95,
    tag: "Men",
    cat: "men",
    colors: ["Sage Green", "Stone Gray", "Arctic White"],
    colorHex: ["#7BAF8E", "#9EAAA5", "#F7F9F8"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    images: [
      "/images/lifestyle-men-outdoor.png",
      "/images/detail-mesh-green.png",
      "/images/proof-ticks.jpg",
    ],
    placeholderBg: "#C8E0EA",
    placeholderEmoji: "🧥",
    description: "Our signature tick-protection pants for men. Featuring an integrated foot cover that seamlessly connects the pant leg to the foot — no gaps, no entry points for ticks. Made from premium noseeum-grade mesh that is breathable, lightweight and completely chemical-free.",
    features: ["Integrated foot cover — no gaps", "Noseeum-grade mesh", "Weight: < 40g", "Breathable & moisture-wicking", "Machine washable at 30°C", "UPF 30+"],
    badge: "Best Seller",
  },
  {
    id: "ba-jacket-men",
    name: "Bug Away Jacket — Men",
    shortName: "Jacket Men",
    price: 74.95,
    tag: "Men",
    cat: "men",
    colors: ["Sage Green", "Stone Gray", "Arctic White"],
    colorHex: ["#7BAF8E", "#9EAAA5", "#F7F9F8"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    images: [
      "/images/product-men-jacket-front.png",
      "/images/product-men-jacket-side.png",
      "/images/product-men-jacket-back.png",
      "/images/product-men-jacket-front-2.png",
      "/images/product-jacket-flatlay.png",
      "/images/detail-zipper.jpg",
    ],
    placeholderBg: "#A8CBB5",
    placeholderEmoji: "🧥",
    description: "Full-coverage mesh jacket for men. Drawstring hood, zip closure and side pockets. Pairs perfectly with our Bug Away Pants for complete 360° tick protection.",
    features: ["Drawstring hood", "Zip closure", "Side pockets", "Noseeum-grade mesh", "Weight: < 45g", "UPF 30+"],
    badge: null,
  },
  {
    id: "ba-pants-women",
    name: "Bug Away Pants — Women",
    shortName: "Pants Women",
    price: 69.95,
    tag: "Women",
    cat: "women",
    colors: ["Sage Green", "Misty Blue", "Arctic White"],
    colorHex: ["#7BAF8E", "#8BB8C8", "#F7F9F8"],
    sizes: ["XS", "S", "M", "L", "XL"],
    images: [
      "/images/product-women-studio.png",
      "/images/lifestyle-women-outdoor.png",
      "/images/detail-mesh-green.png",
    ],
    placeholderBg: "#B8D4CC",
    placeholderEmoji: "🧥",
    description: "Tick-protection pants for women with integrated foot cover. Slim fit, breathable and barely noticeable under regular outdoor clothing.",
    features: ["Integrated foot cover", "Slim fit design", "Noseeum-grade mesh", "Elastic waistband", "Machine washable", "UPF 30+"],
    badge: "New",
  },
  {
    id: "ba-jacket-women",
    name: "Bug Away Jacket — Women",
    shortName: "Jacket Women",
    price: 74.95,
    tag: "Women",
    cat: "women",
    colors: ["Sage Green", "Misty Blue", "Arctic White"],
    colorHex: ["#7BAF8E", "#8BB8C8", "#F7F9F8"],
    sizes: ["XS", "S", "M", "L", "XL"],
    images: [
      "/images/product-women-studio.png",
      "/images/product-jacket-flatlay.png",
      "/images/detail-collage.png",
    ],
    placeholderBg: "#E8F4F8",
    placeholderEmoji: "🧥",
    description: "Lightweight mesh jacket for women. Fitted silhouette, drawstring hood and thumb holes at the cuffs for maximum coverage.",
    features: ["Drawstring hood", "Thumb holes at cuffs", "Zip closure", "Fitted silhouette", "Noseeum-grade mesh", "UPF 30+"],
    badge: null,
  },
  {
    id: "ba-kids-set",
    name: "Bug Away Kids Set",
    shortName: "Kids Set",
    price: 89.95,
    tag: "Kids",
    cat: "kids",
    colors: ["Sage Green", "Sky Blue"],
    colorHex: ["#7BAF8E", "#8BB8C8"],
    sizes: ["2-4Y", "4-6Y", "6-8Y", "8-10Y", "10-12Y"],
    images: [
      "/images/lifestyle-kids-forest.png",
      "/images/detail-mesh-green.png",
    ],
    placeholderBg: "#A8CBB5",
    placeholderEmoji: "👕",
    description: "Complete tick protection for kids. Jacket + pants set designed for safe outdoor play. Safe elastic at the hood (no drawstrings), integrated foot cover and extra pockets for nature treasures.",
    features: ["Jacket + pants included", "Safe elastic hood (no drawstrings)", "Integrated foot cover", "Extra pockets", "Gentle on sensitive skin", "Machine washable"],
    badge: "Set",
  },
  {
    id: "ba-combo-adults",
    name: "Adults Combo Set",
    shortName: "Combo Set",
    price: 129.95,
    tag: "Bundle",
    cat: "bundles",
    colors: ["Sage Green", "Stone Gray"],
    colorHex: ["#7BAF8E", "#9EAAA5"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    images: [
      "/images/lifestyle-couple-forest.png",
      "/images/product-men-jacket-front.png",
      "/images/product-women-studio.png",
    ],
    placeholderBg: "#8BB8C8",
    placeholderEmoji: "🎒",
    description: "Complete tick protection: Bug Away Pants + Bug Away Jacket bundled together. Choose matching colors and save €14.95 compared to buying separately.",
    features: ["Pants + Jacket included", "Save €14.95", "Choose matching colors", "Choose your sizes", "Free shipping", "Gift packaging available"],
    badge: "Save €14.95",
  },
  {
    id: "ba-socks",
    name: "Bug Away Socks",
    shortName: "Socks",
    price: 19.95,
    tag: "Extras",
    cat: "extras",
    colors: ["Sage Green", "White"],
    colorHex: ["#7BAF8E", "#F7F9F8"],
    sizes: ["S (35-38)", "M (39-42)", "L (43-46)"],
    images: ["/images/detail-mesh-green.png"],
    placeholderBg: "#EAEDEB",
    placeholderEmoji: "🧦",
    description: "Extra tick protection at ankle and foot. Wear over or under the integrated foot cover of your Bug Away pants for double protection.",
    features: ["Noseeum-grade mesh", "Reinforced heel and toe", "Anti-slip sole", "Machine washable"],
    badge: null,
  },
  {
    id: "ba-tick-kit",
    name: "Tick Removal Kit",
    shortName: "Tick Kit",
    price: 9.95,
    tag: "Extras",
    cat: "extras",
    colors: [],
    colorHex: [],
    sizes: ["One Size"],
    images: ["/images/proof-ticks.jpg"],
    placeholderBg: "#EAEDEB",
    placeholderEmoji: "🔬",
    description: "Professional tick removal kit. Stainless steel fine-tip tweezers, magnifying glass, disinfectant wipes and compact carry case. Always be prepared.",
    features: ["Fine-tip tweezers", "5x magnifying glass", "Disinfectant wipes (x5)", "Compact carry case", "Instructions included"],
    badge: null,
  },
];

export const reviews = [
  { name:"Marloes V.", loc:"Utrecht", stars:5, text:"Finally something that actually works! I walk my dog in the forest every day and had Lyme disease twice. This clothing makes me feel so much safer. Barely noticeable but incredibly effective.", product:"Adults Combo Set", date:"March 2025" },
  { name:"Jan de B.", loc:"Zeeland", stars:5, text:"Great pants. Fits perfectly, the foot cover is a genuinely smart design detail — exactly what I was looking for. My wife ordered one too within a week.", product:"Bug Away Pants Men", date:"February 2025" },
  { name:"Sofie K.", loc:"Antwerp", stars:5, text:"My kids now play outside without me worrying constantly. The kids set is cute AND functional. So glad I found this before tick season started!", product:"Bug Away Kids Set", date:"April 2025" },
  { name:"Rens M.", loc:"Friesland", stars:4, text:"Light, fine fabric and it works. Ticks simply cannot get through. Ordered a size up as recommended and that was the right call. Very happy.", product:"Bug Away Jacket Men", date:"March 2025" },
  { name:"Emma T.", loc:"Amsterdam", stars:5, text:"I was skeptical at first but after one hike I was convinced. Absolutely unnoticeable under my regular outdoor gear. A must-have for anyone spending time in nature.", product:"Bug Away Pants Women", date:"April 2025" },
  { name:"Pieter H.", loc:"Groningen", stars:5, text:"The whole family now wears Bug Away. Even our golden retriever's owner (that's me) finally feels safe in the forest again. Highly recommend.", product:"Adults Combo Set", date:"March 2025" },
];

export const blogPosts = [
  {
    id: "tick-season-2025",
    slug: "tick-season-2025",
    title: "Tick Season 2025: When Are Ticks Most Active?",
    tag: "Education",
    emoji: "🌱",
    date: "April 2025",
    readTime: "4 min read",
    excerpt: "Ticks become active as soon as temperatures rise above 7°C. Find out when the risk is highest and how to prepare yourself and your family.",
    content: `Ticks are small arachnids that feed on the blood of mammals, birds, and reptiles. In the Netherlands and Belgium, they are primarily active from March through November, with peak activity in spring (April-June) and late summer (August-September).\n\nThe key temperature threshold to remember is 7°C. Once daytime temperatures consistently stay above this level, ticks become active and start looking for hosts.\n\n**Peak risk months:** April, May, June, August, September\n\n**Where to be careful:** Forest edges, tall grass, shrubs, garden hedges, parks with tall vegetation.\n\n**The best protection:** Physical barriers like Bug Away mesh clothing are the most reliable way to prevent tick bites — no chemicals, no side effects, always effective.`,
  },
  {
    id: "recognize-tick-bite",
    slug: "recognize-tick-bite",
    title: "How to Recognize a Tick Bite and What to Do",
    tag: "Health",
    emoji: "🔬",
    date: "March 2025",
    readTime: "5 min read",
    excerpt: "Not every tick bite leads to Lyme disease. But knowing what to do immediately after a bite can make all the difference to your health.",
    content: `A tick bite is often painless — you may not even notice it has happened. This is why regular body checks after spending time outdoors are so important.\n\n**How to check:** After being outside, check warm, moist areas of your body: behind the knees, in the groin area, under the arms, around the waist, behind the ears and the back of the neck.\n\n**If you find a tick:**\n1. Use fine-tipped tweezers (like those in our Tick Removal Kit)\n2. Grip the tick as close to the skin as possible\n3. Pull upward with steady, even pressure — don't twist\n4. Clean the area with alcohol or soap and water\n5. Note the date and location of the bite\n\n**Watch for symptoms:** Monitor the bite area for 4 weeks. A bull's-eye rash (red ring around the bite) is a sign of potential Lyme disease — contact your doctor immediately.`,
  },
  {
    id: "ticks-and-dogs",
    slug: "ticks-and-dogs",
    title: "Ticks and Dogs: Risks and How to Protect Your Pet",
    tag: "Pets",
    emoji: "🐕",
    date: "April 2025",
    readTime: "3 min read",
    excerpt: "Dogs face the exact same tick risks as humans. Discover how to protect your dog against ticks and tick-borne diseases this season.",
    content: `Dogs are highly susceptible to tick bites and can contract several tick-borne diseases including Lyme disease, Ehrlichiosis and Babesiosis. Unlike humans, dogs often cannot communicate when they're feeling unwell, making prevention even more important.\n\n**Signs your dog may have been bitten:** Lethargy, loss of appetite, limping, fever, or swollen joints.\n\n**Prevention tips:**\n- Check your dog thoroughly after every outdoor walk\n- Pay attention to: between toes, inside ears, around the collar area, under the tail\n- Consider spot-on tick treatment from your vet\n- For yourself: wear Bug Away clothing so you don't accidentally transfer ticks from your dog to yourself\n\n**After finding a tick on your dog:** Remove it promptly using fine-tipped tweezers and monitor your dog's health for the next 4-6 weeks.`,
  },
];

export const faqs = [
  {
    category: "Product",
    questions: [
      { q: "How fine is the mesh — will it actually block ticks?", a: "Yes. Our mesh is noseeum-grade, meaning the openings are smaller than the body width of a tick or noseeum midge. Ticks cannot crawl through or penetrate the fabric. Independent testing has confirmed 100% tick blockage when worn correctly." },
      { q: "Is it hot to wear in summer?", a: "Not at all. The mesh is incredibly breathable — in fact, it creates a small air gap between your skin and the fabric which actually helps with cooling. Many customers wear it as a base layer even on warm days without noticing it." },
      { q: "What is the integrated foot cover?", a: "The integrated foot cover means the pant leg and foot cover are one continuous piece of mesh. There is no gap at the ankle — which is the most common entry point for ticks. The foot cover sits snugly over your sock and under your shoe, completely sealing off access." },
      { q: "Does it contain DEET or any chemical repellents?", a: "Absolutely not. Bug Away works purely through physical barrier protection. No DEET, no permethrin, no insecticides of any kind. Safe for children, pregnant women and allergy sufferers." },
      { q: "How do I wash Bug Away clothing?", a: "Machine washable at 30°C on a gentle cycle. Do not tumble dry — air dry only. Do not iron directly on the mesh. The mesh retains its protective properties indefinitely with proper care." },
    ],
  },
  {
    category: "Sizing",
    questions: [
      { q: "How should Bug Away clothing fit?", a: "Bug Away is designed to be worn as a base layer under your regular outdoor clothing. For best protection, it should fit loosely — not tight against the skin. We recommend sizing up if you're between sizes." },
      { q: "Do you have a size guide?", a: "Yes! See our size guide below this FAQ section. We provide measurements for chest, waist, hips and inseam for all sizes." },
    ],
  },
  {
    category: "Shipping & Returns",
    questions: [
      { q: "How long does shipping take?", a: "Netherlands & Belgium: 2-3 business days. Rest of Europe: 4-7 business days. North America: 7-14 business days." },
      { q: "What is your return policy?", a: "We offer a 30-day no-questions-asked return policy on unworn items. If your Bug Away clothing doesn't meet your expectations, simply return it for a full refund or exchange." },
      { q: "Is shipping free?", a: "Free shipping on all orders over €59 within the Netherlands and Belgium. International shipping rates are calculated at checkout." },
    ],
  },
  {
    category: "Lyme Disease",
    questions: [
      { q: "Does Bug Away prevent Lyme disease?", a: "Bug Away prevents tick bites, which is the primary way Lyme disease is transmitted to humans. By creating a physical barrier that ticks cannot penetrate, it significantly reduces your risk. No product can offer 100% protection against all tick-borne diseases, but Bug Away is one of the most effective preventative measures available." },
      { q: "I already have Lyme disease — can Bug Away help?", a: "Bug Away prevents new tick bites, which is important even if you already have Lyme disease — reinfection or co-infection with other tick-borne diseases can complicate treatment and recovery. Please consult your doctor for treatment of existing Lyme disease." },
    ],
  },
];
